version: '3'
services:
  
  database:
    image: mariadb:10.6.1
    restart: unless-stopped
    container_name: mariadb-container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "common_app"
    volumes:
      - ./.volumes/database:/var/lib/mysql

  api:
    image: maven:3.8.3
    restart: unless-stopped
    container_name: sier-web
    links:
      - database
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      DB_URL: "database:3306/sier"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
    volumes:
      - ./:/app
      - ./.volumes/maven:/root/.m2
    working_dir: /app
    command: mvn spring-boot:run